service: notification-service

plugins:
  - serverless-offline
  - serverless-lift

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  profile: trengym

functions:
  compute:
    handler: dist/main.ts
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - transactionQueue
              - Arn
          batchSize: 10
          functionResponseType: ReportBatchItemFailures

resources:
  Resources:
    transactionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: transactionQueue.fifo
        FifoQueue: true
